- name: MYSQL
  hosts: localhost 
  become: yes
  
  tasks:

    - name: Install mysql server
      ansible.builtin.dnf:
        name: mysql-server
        state: installed

    - name: Start mysql service
      ansible.builtin.systemd_service:
        name: mysqld
        state: started    
        enabled: yes

#    - name: Change the default mysql password
#      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1

    - name: change default password
      mysql_secure_installation:
        login_password: ''
        new_password: ExpenseApp@1
        user: root
        login_host: localhost
